/// Flutter icons VMSIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VMSIcons
///      fonts:
///       - asset: fonts/VMSIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class VMSIcons {
  VMSIcons._();

  static const _kFontFam = 'VMSIcons';
  static const String? _kFontPkg = null;

  static const IconData approve =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_2 =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData option_dot =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData presention_chart =
      IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xeba5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase =
      IconData(0xeba6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xeba7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document =
      IconData(0xeba8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_1 =
      IconData(0xeba9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash =
      IconData(0xebaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData importance =
      IconData(0xebab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xebac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout =
      IconData(0xebad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor_mobbile =
      IconData(0xebae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xebaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_1 =
      IconData(0xebb0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan_barcode =
      IconData(0xebb1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xebb2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_image =
      IconData(0xebb3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back =
      IconData(0xebb4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buliding =
      IconData(0xebb5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homepage =
      IconData(0xebb6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct =
      IconData(0xebb7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_element =
      IconData(0xebb8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_outline =
      IconData(0xebb9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck =
      IconData(0xebba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData missing_key =
      IconData(0xebbb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData land_key =
      IconData(0xebbc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xebbd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_plus =
      IconData(0xebbe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_plus =
      IconData(0xebbf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_Filled =
      IconData(0xebc0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
